#!/bin/sh

CMD="qdb/bin/qdbd"
ARGS="-c qdbd.conf"

echo "Cleaning up..."
pkill -SIGKILL -f qdbd
rm -rf qdb/db \
    && mkdir -p qdb/db

echo "Starting qdbd..."
$CMD $ARGS 1>qdbd.out.txt 2>qdbd.err.txt &
